version: '3.5'

services:
  kurki:
    build:
      context: ./
    ports:
      - 8084:8080
    volumes:
      - ./kurki.cnf:/usr/local/tomcat/webapps/ROOT/WEB-INF/kurki.cnf
    container_name: kurki
  kurki-db:
    image: banglamon/oracle193db:19.3.0-ee
    environment:
      ORACLE_SID: opetest2
      ORACLE_PBD: tk_opha
      ORACLE_PWD: oracle
    volumes:
      - ./oracle_data:/u01/app/oracle/oradata
      - ./scripts/fetch_db.sh:/fetch_db.sh:ro
    container_name: kurki-db
  loginas:
    build:
      context: ./loginas
    environment:
      UID: ahslaaks
    ports:
      - "3003:3000"
    volumes:
      - ./loginas:/usr/src/app
      - loginas-nodemod:/usr/src/app/node_modules
    container_name: loginas
  kurki-updater:
    build:
      context: updater
      dockerfile: config/dev.Dockerfile
    environment:
      KURKI_DB_USER: tk_opha
      KURKI_DB_PASSWORD: salasana
      KURKI_DB_CONNECTION_STRING: kurki-db:1521/opetest2
      KURKI_FALLBACK_KURSSI_OMISTAJA: SIVEN_R
      SIS_IMPORTER_API_URL: https://importer.cs.helsinki.fi
    volumes:
      - ./updater:/usr/src/app
      - updater-nodemod:/usr/src/app/node_modules/
    container_name: kurki-updater
    depends_on:
      - kurki-db

volumes:
  oracle_data:
  updater-nodemod:
  loginas-nodemod:

#networks:
#  default:
#    external:
#      name: sis-importer_default